<a href="https://colab.research.google.com/github/soon15/2024-intro-DA-code/blob/main/w03_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#다차원 배열 ndarray

In [2]:
import numpy as np

a = np.ndarray(shape=(2, 2), dtype=int)
a

array([[ 96258966053098,               0],
       [133532403135337, 138167554069504]])

#내장함수 array()로 ndarray 생성

In [3]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [6]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [7]:
a.data

In [8]:
import numpy as np

np.array(1, 2, 3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
np.array([1, 'py', 3.14])

In [ ]:
lang = np.array(['파이썬', '자바', '씨'])
lang

In [ ]:
lang = np.array(['파이썬', '자바', '씨'], dtype=str)
lang

In [ ]:
a = np.array((1, 2, 3), dtype=float)
a

In [ ]:
b = np.array((1, 2.5, 3))
b

#내장함수 arange() 활용

In [9]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [10]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [11]:
import numpy as np

a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
np.reshape(a, (2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [13]:
np.reshape(a, (3, 5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [ ]:
np.reshape(a, (2, 6))

In [ ]:
b = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)
b

In [14]:
np.reshape(b, (2, -1))

NameError: name 'b' is not defined

#내장함수 linspace() 활용

In [ ]:
import numpy as np

np.linspace(2.0, 3.0)

In [ ]:
np.linspace(2.0, 3.0, retstep=True)

In [ ]:
print( (3-2) / (50-1) )

In [ ]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

In [15]:
print( (3-2) / 50 )

0.02


In [16]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [17]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

#내장함수 arange()와 linspace() 비교

In [18]:
np.arange(0.1, 0.4, 0.1)

array([0.1, 0.2, 0.3, 0.4])

In [19]:
np.arange(1, 4, 1) / 10.0

array([0.1, 0.2, 0.3])

In [21]:
np.linspace(0.1, 0.4, 3, endpoint=False)

array([0.1, 0.2, 0.3])

In [22]:
np.linspace(0.1, 0.4, 4)

array([0.1, 0.2, 0.3, 0.4])

#end of code