<a href="https://colab.research.google.com/github/soon15/2024-intro-DA-code/blob/main/w03_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#범용 함수

In [6]:
import numpy as np

a = np.array([1, 4, 9])
np.sqrt(a)

array([1., 2., 3.])

In [7]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [8]:
import numpy as np

a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [9]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [11]:
np.add(a, b)

array([ 3,  6, 11])

In [12]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [13]:
np.power(a, b)

array([ 1, 16, 81])

#1차원 배열의 첨자와 슬라이싱

In [14]:
import numpy as np

a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
print(a[3])
print(a[-2])

9
64


In [16]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [17]:
a[::-2]

array([81, 49, 25,  9,  1])

In [18]:
a[2:5] = -100

In [21]:
a[2:5] = [-5, -5]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [22]:
b = np.array([5] * 10)
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [23]:
b[::2] = -10
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [25]:
b[::2] = np.arange(5)
b

array([0, 5, 1, 5, 2, 5, 3, 5, 4, 5])

#2차원 배열의 첨자와 슬라이싱

In [26]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [27]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [28]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [29]:
a[-2, : ]

array([18, 19, 20, 21, 22, 23])

In [30]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [31]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [33]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [34]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [35]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [36]:
a[2, 4]

16

In [37]:
a[2][4]

16

In [38]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [39]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [40]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

#3차원 배열의 첨자와 슬라이싱

In [43]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [44]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [45]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [46]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [47]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [48]:
a[1, ..., 1]

array([13, 17, 21])

In [49]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#1차원 배열로 만드는 ndarray.ravel()

In [53]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [54]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

np.transpose(a)와 a.transpose(), a.T

In [55]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [57]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [58]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
np.transpose(a, (0, 1))

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.transpose(a, (1, 0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [61]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [62]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [63]:
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [65]:
np.transpose(b, (2, 1, 0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [66]:
np.transpose(b, (0, 2,1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [68]:
c = np.arange(1, 13).reshape(2, 2, 3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
c.transpose((1, 2, 0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [72]:
np.transpose(c, (1, 2, 0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [73]:
np.transpose(c)

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

#np.swapaxes()

In [74]:
x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [75]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [76]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [77]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [78]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [79]:
np.transpose(x, (2, 1, 0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

#ndarray의 데이터와 메타데이터

In [80]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [81]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [82]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [83]:
org

array([  0,   1, 200,   3,   4])

#복사(copy)

In [84]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [85]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [86]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [87]:
org

array([0, 1, 2, 3, 4])

#배열이 뷰인지 복사본인지 확인하는 방법

In [88]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [89]:
y = x.reshape(2, 3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [90]:
y.base

array([0, 1, 2, 3, 4, 5])

In [91]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [92]:
c = z.copy()
print(c.base)

None


#ndarray의 보기로 같은 구조만 수정 가능

In [93]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [94]:
lst[3:5] = [30, 40, 50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [95]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [96]:
x[3:5] = [30, 40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [97]:
x[3:5] = [30, 40, 50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

#얕은 복사(shallow copy)

In [98]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
b = a
b is a

True

In [100]:
print(id(a))
print(id(b))

139895407590160
139895407590160


In [101]:
print(b.base)

None


In [102]:
b[0,0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [103]:
v = a.reshape(3, 2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [104]:
print(id(a))
print(id(v))

139895407590160
139895407722928


In [105]:
v[0,1] = 200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [106]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

#End of Code