<a href="https://colab.research.google.com/github/soon15/2024-intro-DA-code/blob/main/w03_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#함수 arange()와 linspace() 비교

In [2]:
import numpy as np

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [3]:
a.dtype

dtype('float64')

In [4]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [7]:
b = np.zeros((2, 1))
b

array([[0.],
       [0.]])

In [8]:
b.shape

(2, 1)

#원소가 모두 1인 배열을 생성하는 ones()

In [9]:
import numpy as np

np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

#대각선 원소가 모두 1인 2차원 배열을 생성하는 eye()

In [10]:
import numpy as np

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [12]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [13]:
a = np.eye(3, 4, 1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
a = np.eye(3, 4, -1)
a

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

#원소가 모두 1인 배열을 생성하는 full()

In [15]:
import numpy as np

np.full([2, 3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [16]:
np.full([2,3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [17]:
np.full([3, 4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [18]:
np.full([4, 3], fill_value = np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

#원소가 모두 1인 배열을 생성하는 empty()

In [19]:
import numpy as np

np.empty([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [20]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [21]:
np.empty([2, 3], dtype=int)

array([[     95958151051820,                   0,     136756384550112],
       [    136756384550112, 3904957750092968035,     136756949364787]])

#원소값이 0인 주어진 형태의 배열을 생성하는 zeros_like()

In [22]:
import numpy as np

a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

#원소값이 1인 주어진 형태의 배열을 생성하는 ones_like()

In [24]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

#원소값이 주어진 값이며 주어진 형태의 배열을 생성하는 full_like()

In [26]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

#배열과 스칼라와의 연산

In [27]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [28]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


#배열과 배열의 연산

In [29]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
b = np.full_like(a, [1, 2, 3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [31]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [32]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [33]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [34]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [35]:
b += a
b

array([0.5, 2.5, 4.5, 6.5])

In [37]:
a = np.full((2, 3), [1, 2, 3])

In [39]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [40]:
a @ b

array([[12,  6],
       [12,  6]])

In [41]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [42]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

#배열 함수

In [43]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [44]:
a.sum()

46

In [45]:
a.sum(axis=0)

array([16, 30])

In [48]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


In [50]:
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [51]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [52]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [53]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

#End of Code