<a href="https://colab.research.google.com/github/soon15/2024-intro-DA-code/blob/main/w04_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#row_stack()과 vstack()

In [3]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [5]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

#np.c[]와 np.column_stack()

In [6]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [7]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [10]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [11]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [12]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

#np.r_[] 개요

In [13]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [14]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [15]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [16]:
np.row_stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [18]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [19]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [20]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

#np.r_['i, j, k', a, b]

In [21]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [23]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [24]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [25]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [26]:
np.r_['0, 2', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.r_['0, 2', [1, 2, 3], [4, 5, 6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
np.r_['0, 3', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [30]:
np.r_['1, 3, 0', [1, 2, 3], [4, 5, 6]]

array([[[1],
        [4]],

       [[2],
        [5]],

       [[3],
        [6]]])

In [31]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [32]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

#여러 1차원 배열을 수평 방향으로 합치는 방법

In [34]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [35]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [36]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [37]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

#여러 1차원 배열을 수직 방향으로 합치는 방법

In [38]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [39]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.row_stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

#여러 1차원 배열을 행으로 확장해 수평 방향으로 합치는 방법

In [42]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [43]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [47]:
np.concatenate(((a[:, np.newaxis], b[:, np.newaxis])), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

#End of Code